dist: trusty
language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox
os:
  - linux
#  - osx
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_block_store_service
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_block_store_service
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_block_store_service
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_cloud_factory
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_cloud_factory
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_cloud_factory
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_cloud_helpers
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_cloud_helpers
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_cloud_helpers
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_compute_service
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_compute_service
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_compute_service
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_interface
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_interface
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_interface
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_network_service
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_network_service
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_network_service
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_object_life_cycle
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_object_life_cycle
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_object_life_cycle
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_object_store_service
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_object_store_service
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_object_store_service
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_region_service
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_region_service
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_region_service
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_security_service
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_security_service
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_security_service
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_vm_types_service
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_vm_types_service
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_vm_types_service
    - python: 2.7
      env: TOX_ENV=py27-aws TOX_TEST=test.test_image_service
    - python: 2.7
      env: TOX_ENV=py27-azure TOX_TEST=test.test_image_service
    - python: 2.7
      env: TOX_ENV=py27-openstack TOX_TEST=test.test_image_service
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_block_store_service
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_block_store_service
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_block_store_service
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_cloud_factory
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_cloud_factory
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_cloud_factory
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_cloud_helpers
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_cloud_helpers
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_cloud_helpers
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_compute_service
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_compute_service
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_compute_service
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_interface
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_interface
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_interface
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_network_service
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_network_service
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_network_service
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_object_life_cycle
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_object_life_cycle
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_object_life_cycle
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_object_store_service
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_object_store_service
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_object_store_service
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_region_service
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_region_service
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_region_service
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_security_service
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_security_service
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_security_service
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_vm_types_service
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_vm_types_service
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_vm_types_service
    - python: 3.6
      env: TOX_ENV=py36-aws TOX_TEST=test.test_image_service
    - python: 3.6
      env: TOX_ENV=py36-azure TOX_TEST=test.test_image_service
    - python: 3.6
      env: TOX_ENV=py36-openstack TOX_TEST=test.test_image_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_block_store_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_block_store_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_block_store_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_cloud_factory
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_cloud_factory
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_cloud_factory
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_cloud_helpers
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_cloud_helpers
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_cloud_helpers
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_compute_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_compute_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_compute_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_interface
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_interface
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_interface
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_network_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_network_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_network_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_object_life_cycle
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_object_life_cycle
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_object_life_cycle
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_object_store_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_object_store_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_object_store_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_region_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_region_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_region_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_security_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_security_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_security_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_vm_types_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_vm_types_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_vm_types_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-aws TOX_TEST=test.test_image_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-azure TOX_TEST=test.test_image_service
    - python: pypy-5.3.1
      env: TOX_ENV=pypy-openstack TOX_TEST=test.test_image_service
before_install:
    - |
      case "$TRAVIS_EVENT_TYPE" in
        push|pull_request)
           # Check whether we need to run a test for this provider
           DOCS_REGEX='(\.rst$)|(^(docs))/'
           FILES_IN_CHANGESET="`git diff --name-only $TRAVIS_COMMIT_RANGE`"
           echo "$FILES_IN_CHANGESET" | grep -qvE "$DOCS_REGEX" || {
              echo "Only docs were updated. Stopping build process."
              exit
           }
           echo "$FILES_IN_CHANGESET" | grep -qvE "$DOCS_REGEX|(^(cloudbridge/cloud/providers))" || {
              echo "Only docs and providers were updated. Checking whether this provider was changed."
              # Extract env and provider from $TOXENV into $PYENV and $PROVIDER respectively
              IFS=- read PYENV PROVIDER <<< "$TOX_ENV"
              echo "$FILES_IN_CHANGESET" | grep -qE "^(cloudbridge/cloud/providers/$PROVIDER)" && {
                 echo "This provider was affected by this changeset. Running tests."
              } || {
                 echo "This provider was not affected by this changeset. Stopping build process."
                 exit
              }
           }
           ;;
        *)
           echo "Build triggered through API or CRON job. Running regardless of changes"
           ;;
      esac
install:
    - pip install --upgrade pip
    - pip install -U setuptools
    - pip install tox
    - pip install coveralls
    - pip install codecov
script:
    - travis_wait 50 tox -e $TOX_ENV -- --tests $TOX_TEST
after_script:
    - |
      case "$TRAVIS_EVENT_TYPE" in
        push|pull_request)
           # Don't run coverage if tests or cloudbridge interface was not affected
           DOCS_REGEX='(\.rst$)|(^(docs))/'
           FILES_IN_CHANGESET="`git diff --name-only $TRAVIS_COMMIT_RANGE`"
           echo "$FILES_IN_CHANGESET" | grep -qvE "$DOCS_REGEX|(^(cloudbridge/cloud/providers))" && {
              coveralls &
              codecov &
              wait
           } || {
              echo "Only docs and providers were updated. Not running coverage."
           }
           ;;
        *)
           echo "Build triggered through API or CRON job. Running regardless of changes"
           coveralls & codecov & wait
           ;;
      esac

