name: coverage

# Run this workflow at the end when all integration tests finish
on:
  workflow_run:
    workflows: ["aws", "azure", "gcp", "mock", "openstack"]
    types:
      - completed

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  coverage:
    # Run only if previous step succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
