name: Integration

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  integration:
    # Name the Job
    name: Run mock integration tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
        cloud-provider: ['aws', 'azure', 'gcp', 'mock', 'openstack']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python-version }}

      - name: Cache pip dir
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('**/setup.py', '**/requirements.txt') }}

      - name: Install required packages
        run: pip install tox

      - name: Run tox
        run: tox -e ${{ matrix.python-version }}-${{ cloud-provider }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.python-version }}-${{ cloud-provider }}
          parallel: true

  finish:
    needs: integration
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
